{
 "title": "Jails",
 "description": "FreeBSD jail metrics as reported by rctl",
 "tags": [
  "jail",
  "freebsd"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jail_num, instance)"
   },
   {
    "name": "jail",
    "label": "Jail",
    "query": "label_values(jail_id{instance=\"$instance\"}, name)"
   },
   {
    "name": "version",
    "label": "version",
    "query": "label_values(jail_exporter_build_info{instance=\"$instance\"}, version)"
   }
  ]
 },
 "panels": [
  { "title": "Current Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Jails",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jail_num" }
   ]
  },
  {
   "title": "%CPU Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_pcpu_used{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_memoryuse_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Virtual Memory Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_vmemoryuse_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Shared Memory Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_shmsize_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_maxproc{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_nthr{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_openfiles{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Swap Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jail_swapuse_bytes{instance=\"$instance\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU % (pcpu)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "%CPU used" }
   ],
   "targets": [
    {
     "expr": "jail_pcpu_used{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Seconds (cputime)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "seconds used" }
   ],
   "targets": [
    {
     "expr": "rate(jail_cputime_seconds_total{instance=\"$instance\",name=~\"$jail\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory (memoryuse)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "bytes used" }
   ],
   "targets": [
    {
     "expr": "jail_memoryuse_bytes{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Virtual Memory (vmemoryuse)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "bytes used" }
   ],
   "targets": [
    {
     "expr": "jail_vmemoryuse_bytes{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swap (swapuse)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "bytes used" }
   ],
   "targets": [
    {
     "expr": "jail_swapuse_bytes{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shared Memory (shmsize)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes", "label": "bytes used" }
   ],
   "targets": [
    {
     "expr": "jail_shmsize_bytes{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Process State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Processes (maxproc)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jail_maxproc{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Threads (nthr)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jail_nthr{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Open Files (openfiles)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jail_openfiles{instance=\"$instance\",name=~\"$jail\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } }
 ]
}