#!/bin/sh
#
#

# PROVIDE: os-release
# REQUIRE: mountcritremote FILESYSTEMS
# BEFORE:  LOGIN

. /etc/rc.subr

name="osrelease"
desc="os-release update"
rcvar="osrelease_enable"
start_cmd="osrelease_start"
stop_cmd=":"

load_rc_config $name

: ${osrelease_file:=/var/run/os-release}
: ${osrelease_perms:=444}
: ${osrelease_home_url:="https://hardenedbsd.org/"}
: ${osrelease_documentation_url:="https://radicle.network/nodes/rad.hardenedbsd.org/docs"}
: ${osrelease_support_url:="mailto:users@hardenedbsd.org"}
: ${osrelease_bug_report_url:="https://radicle.network/nodes/rad.hardenedbsd.org/src/issues"}

osrelease_start()
{
	local _version _version_id

	startmsg -n "Updating ${osrelease_file} "
	_version=$(freebsd-version -u)
	_version_id=${_version%%[^0-9.]*}
	t=$(mktemp -t os-release)
	cat > "$t" <<-__EOF__
		NAME=HardenedBSD
		VERSION="$_version"
		VERSION_ID="$_version_id"
		ID=hardenedbsd
		ANSI_COLOR="0;31"
		PRETTY_NAME="HardenedBSD $_version"
		CPE_NAME="cpe:/o:freebsd:freebsd:$_version_id"
		HOME_URL="${osrelease_home_url}"
		DOCUMENTATION_URL="${osrelease_documentation_url}"
		SUPPORT_URL="${osrelease_support_url}"
		BUG_REPORT_URL="${osrelease_bug_report_url}"
__EOF__
	install -C -o root -g wheel -m ${osrelease_perms} "$t" "${osrelease_file}"
	rm -f "$t"
	startmsg 'done.'
}

# doesn't make sense to run in a svcj: config setting
osrelease_svcj="NO"

run_rc_command "$1"
